name 'mapserver'
maintainer 'Shaw Innes'
maintainer_email 'shaw@immortal.net.au'
license 'all_rights'
description 'Installs/Configures MapServer'
long_description 'Installs/Configures MapServer'
version '0.1.0'
